### ISSUE TITLE
Detecting Node.JS app.

### ISSUE THREAD

**Issue by FLYBYME** [heroku/heroku-buildpack-go#10]
Im trying to run this buildpack on this project https://github.com/c9/core.

The project is a nodejs app but because it has a *.go file its been detected as a go app.

I don't think the detection is as good as it could be. Maybe just look in the bin folder or root folder for a go file.

**Comment by dmathieu** [comment]
Hi,

Go is not one of our official buildpacks. You can find that list here:
https://devcenter.heroku.com/articles/buildpacks#default-buildpacks
Are you sure there isn't a `BUILDPACK_URL` config variable defined on your app?

If Go were a default buildpack though, this issue could happen anyway. When compiling your app, we take all our default buildpacks in the order specified in our documentation and for each of them, execute the `bin/detect` executable.
The first matching buildpack will be the one used. We display a warning if multiple buildpacks are detected.

This is not a buildpack issue, so I'm going to close it.
I would recommend to open a support request at https://help.heroku.com, with your app name. We will be better able to help you by looking at your app's configuration.

**Comment by FLYBYME** [comment]
I'm not using heroku. And it is a bug.

**Comment by dmathieu** [comment]
Tim,

Could you better describe your use case then?
Whatever platform you're using with this buildpack, you should probably lookup their own way of explicitely specifying the nodejs one.
