### ISSUE TITLE
use wildcard for patch-level versioning

### ISSUE THREAD

**Issue by jtarchie** [heroku/heroku-buildpack-go#100]
Given I'm a Goalng app developer,
When I push my app to a cloud platform with `"GoVersion": "1.4.*"`,
Then the golang buildpack should select the latest stable 1.4.x of golang,
And successfully stage the app.

This is reference to the [discussion](https://github.com/tools/godep/issues/297) on `godeps` with @freeformz .

**Comment by kr** [comment]
Consider redefining godep's behavior from "record whatever 'go version' says" to "record the version string of the major release of Go being used" (but not the minor revision, if one is being used). So if the user is using Go 1.5.1, it would record `1.5` in the GoVersion field.

Then buildpacks can pick whatever minor revision they want. (Probably always the newest one.) It should be _extremely_ rare for a user to legitimately want a version of Go that's not the latest minor revision within whatever major release they're on. IMO it's fine for the buildpack to simply not support that scenario. It's not so hard to fork the buildpack if you need such super-fine control over the Go distribution.

**Comment by kr** [comment]
(If I could go back in time, I would have done it that way from the start.)

**Comment by flavorjones** [comment]
@kr I like this idea as well. Would you accept a PR that would simply save `major.minor` in the GoVersion field?

**Comment by jtarchie** [comment]
Taken from the discussion on [PR](https://github.com/tools/godep/pull/318):

@freeformz what were you thinking this has to come in after the buildpack supports it? It is a bit of the chicken an egg problem, I guess. In my humble opinion, the minor version resolution should happen in the buildpack and not via some third party service, like the nodejs buildpack does.

**Comment by jtarchie** [comment]
@freeformz, do you have an idea how we would evaluate the latest minor release based only the major version?

Some ideas:
1. just keep track of all the current versions in the script
2. 3rd party API, like the nodejs buildpack, but I don't relying on external service because if it is down, you cannot deploy your app
3. if the current version does not download, add increment/decrement minor and retry download

The first option, we'd be able to do. The CloudFoundry fork locks the versions of the support golang binaries, so the meta information is already available. The only change to the Heroku buildpack workflow is someone would have to manually update the supported `GO_VERSIONS` (imaginary env var), which could also be a CI job, too.

**Comment by freeformz** [comment]
@jtarchie I'm going to close this. Changes late last year to godep and the buildpack allow specifying only the major version of go.

**Comment by jtarchie** [comment]
Thanks @freeformz, the Cloud Foundry team just released their support for the feature, too. We read the version numbers that we support for go from a [manifest](https://github.com/cloudfoundry/go-buildpack/blob/master/manifest.yml).

Thanks for all the work!
