### ISSUE TITLE
licensing for package `godep`

### ISSUE THREAD

**Issue by jtarchie** [heroku/heroku-buildpack-go#103]
The godep [License](https://github.com/tools/godep/blob/master/License) on clause 2, specifies that the license file must appear in the disclaimer/documentation of the code that is including it as a binary.

The binary [godep](https://github.com/cloudfoundry/go-buildpack/blob/master/linux-amd64/bin/godep) is being packaged with the buildpack.

The buildpack should be including the license, for legalese reasons. 

Some of the maintainers (@kr and @freeformz) are maintainers of godep, too. That might cover legal precedent for them, but for other consumers of the buildpack, the licensing needs to be preserved.

**Comment by jtarchie** [comment]
Thank you. @flavorjones ^^^

**Comment by flavorjones** [comment]
:thumbsup:
