### ISSUE TITLE
Add glide support

### ISSUE THREAD

**Issue by pspeter3** [heroku/heroku-buildpack-go#106]
[Glide](https://github.com/Masterminds/glide) is a well thought out Go 1.5 package manager that seems like a good choice for applications and Heroku buildpack support would be great.

**Comment by erbridge** [comment]
My fork has been hacked together to do that, FYI: https://github.com/erbridge/heroku-buildpack-go

**Comment by freeformz** [comment]
It's something we (Heroku) would have to support beyond just being able to build code via the buildpack. ATM we're not ready to support it.

I'd encourage Heroku users to open a support ticket asking for this if they want it.

If there is enough interest we'll certainly consider supporting it.

In the meantime there are community supported buildpacks/forks that offer it.

**Comment by krancour** [comment]
I know this is closed, but +1 on this.  It would be nice to see this supported in the _official_ go buildpack.

**Comment by freeformz** [comment]
FWIW: I'm planning on starting this after support for govendor, which I hope to start soon.

**Comment by dfuentes77** [comment]
:+1: Govendor and Glide would be great alongside Godep support since they seem to be a bit more mature in features.

**Comment by freeformz** [comment]
WIP: https://github.com/heroku/heroku-buildpack-go/tree/govendor2

**Comment by raphaeljlps** [comment]
any updates on the progress ?

**Comment by freeformz** [comment]
govendor is supported by the buildpack and has some supporting docs. Glide is up next.

**Comment by freeformz** [comment]
Closed by 8aab99452d54c54d7f469e91505a5b4bc30b2672. On master right now, need to get a bunch of internal stuff in line before releasing officially though.

**Comment by francknouama** [comment]
+1 on this

**Comment by flockonus** [comment]
Happy you are supporting Glide!

Looks like it's didn't make into [Heroku - Go documentation](https://devcenter.heroku.com/articles/go-support) tho, took me some googling to find this issue

**Comment by dfuentes77** [comment]
same here.  would love official documentation on using Glide

**Comment by client9** [comment]
For those watching at home, Glide seems to work "as-is"  The build output references this article:

https://devcenter.heroku.com/articles/go-dependencies-via-glide

but it's "Coming Soon :tm:"

```
remote: Building source:
remote:
remote: -----> Go app detected
remote:  !!
remote:  !!    'GOVERSION' isn't set, defaulting to 'go1.8.1'
remote:  !!
remote:  !!    Run 'heroku config:set GOVERSION=goX.Y' to set the Go version to use
remote:  !!    for future builds
remote:  !!
remote: -----> Using go1.8.1
remote: -----> Using glide v0.12.3
remote: -----> Using hg v3.9
remote:  !!    Installing package '.' (default)
remote:  !!
remote:  !!    To install a different package spec for the next build run:
remote:  !!
remote:  !!    'heroku config:set GO_INSTALL_PACKAGE_SPEC="<pkg spec>"'
remote:  !!
remote:  !!    For more details see: https://devcenter.heroku.com/articles/go-dependencies-via-glide
remote:  !!
remote: -----> Fetching any unsaved dependencies (glide install)
```

**Comment by freeformz** [comment]
I updated [that article](https://devcenter.heroku.com/articles/go-dependencies-via-glide) to better represent reality. If you have issues with a Go app and Glide, the best way to ask questions is to open an issue [here](https://github.com/heroku/heroku-buildpack-go/issues/new).
