### ISSUE TITLE
GO15VENDOREXPERIMENT is now default with Go 1.6

### ISSUE THREAD

**Issue by aeneasr** [heroku/heroku-buildpack-go#112]
However I'm getting:

```
-----> Go app detected

-----> Checking Godeps/Godeps.json file.

-----> Installing go1.6... done

-----> Running: go install -v -tags heroku ./...

vendor/github.com/RangelReale/osin/example/osincliclient/osincliclient.go:11:2: cannot find package "github.com/RangelReale/osincli" in any of:

/tmp/build_**********/*****/.heroku/go/src/github.com/ory-am/hydra/vendor/github.com/RangelReale/osincli (vendor tree)
```

**Comment by aeneasr** [comment]
I've added `GO15VENDOREXPERIMENT=1` to the env vars in heroku, still same error..maybe I'm doing something wrong?

**Comment by freeformz** [comment]
Which version of godep did you use (godep version) to create / update the repo?

What are the contents of Godeps/Godeps.jon?

PS: It's probably best to open a ticket at help.heroku.com

**Comment by freeformz** [comment]
You also probably don't want to be using ./... as your package spec as that will try to compile non required files in vendor (which shouldn't be vendored in the first place). 

Where in your repo are you main package(s) ?

**Comment by aeneasr** [comment]
Hey thanks for the super-quick reply. Here's my godep: https://github.com/ory-am/hydra/blob/heroku/Godeps/Godeps.json

What do you mean by _package spec_ in:

> You also probably don't want to be using ./... as your package spec as that will try to compile non required files in vendor (which shouldn't be vendored in the first place). 

Regarding main packages:

> Where in your repo are you main package(s) ?

They (multiple executables) are in subdirectories `./cli/hydra-host`, `./cli/hydra-logon`, ... but only `hydra-host` must be executed.

**Comment by aeneasr** [comment]
I think the way to hotfix this bug right now is with `$ go <cmd> $(go list ./... | grep -v /vendor/)`

**Comment by freeformz** [comment]
re: package spec: `godep save <args>`. The `<args>` are the package spec(s) you've asked godep to save. You probably want to run `godep save ./cli/...` instead of `./...` and then everything will DTRT.

**Comment by aeneasr** [comment]
Ah nice, I didn't know that! Thanks I'll try that!

**Comment by aeneasr** [comment]
Perfect, this seems to be working. Thanks for the hint, should I document this somewhere?

**Comment by freeformz** [comment]
I've updated some of the devcenter.heroku.com articles to remove traces of ./..., but I should probably call it out somewhere. Thoughts?

**Comment by aeneasr** [comment]
Hm maybe in the buildpack readme? And in the devcenter as well? Maybe as an FAQ section or something (I've seen this issue on SO as well, but without solution)
