### ISSUE TITLE
Go application not detected according to README requirements

### ISSUE THREAD

**Issue by ngauthier** [heroku/heroku-buildpack-go#115]
Hi!

In the readme, it states:

> This buildpack will detect your repository as Go if it contains a .go file.

However, this is not true, as in `detect` it checks for Godeps or gb configurations. That means that if a simple repo with only `main.go` in it is tested, `detect` will fail. The repo must either have a Godeps folder and Godeps.json, or a src directory with a go file in it.

I am happy to make a PR, but please let me know which you would prefer:
1. Change README to reflect actual behavior
2. Add `detect` line to find go files in the root
3. Something else?

Thanks!
:heart: @ngauthier

**Comment by freeformz** [comment]
It would have to be #1 or #3. It's very possible to get valid go repos that contain no .go files in the **root** of the repo. We also shouldn't blindly search for any .go files either and I've seen valid repos that are ruby apps that contain .go files. I am open to other suggestions or improvements though.

**Comment by ngauthier** [comment]
After digging more I realized your compile system depends on godeps or gb, so we'd have to write a new one for when those aren't present. I'll submit a pr to update the readme.

**Comment by freeformz** [comment]
At the very least the `Godeps.json` file is required with some minimal info, see here: https://github.com/heroku/heroku-buildpack-go/issues/114#issuecomment-196542765
