### ISSUE TITLE
Go Buildpack Test Suite not passing when run in dyno

### ISSUE THREAD

**Issue by RochesterinNYC** [heroku/heroku-buildpack-go#121]
Hi, I'm running the heroku go buildpack test suite in a dyno as per the instructions in https://github.com/heroku/heroku-buildpack-testrunner#running-buildpack-tests-on-heroku, and the test suite does not pass. Is there some configuration or run step that I am missing or is this the current expected state of the test suite?

``` bash
$ pwd
/Users/user/workspace/heroku-buildpack-go

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

$ heroku create --buildpack https://github.com/heroku/heroku-buildpack-testrunner
Creating app... ⬢ powerful-ocean-53670
Setting buildpack to https://github.com/heroku/heroku-buildpack-testrunner... done
https://powerful-ocean-53670.herokuapp.com/ | https://git.heroku.com/powerful-ocean-53670.git

$ git push heroku master
Everything up-to-date

$ heroku run tests
Running tests on radiant-cliffs-88419... up, run.3260

BUILDPACK: .
  TEST SUITE: compile_test.sh
  testCompileGodepsApp
  ASSERT:Expected STD_ERR to be empty; was < !
   !     Deprecated or unsupported version of go (go1.1)
   !     See https://devcenter.heroku.com/articles/go-support#go-versions for supported version information.
   !
   !     Installing package '.' (default)> expected:<> but was:< !
   !     Deprecated or unsupported version of go (go1.1)
   !     See https://devcenter.heroku.com/articles/go-support#go-versions for supported version information.
   !
   !     Installing package '.' (default)>
  ASSERT:should run godep go install
  testCompileGodirApp
  ASSERT:Expected captured exit code to be 0; was <1> expected:<0> but was:<1>
  ASSERT:Expected STD_ERR to be empty; was < !     Godep, GB or govendor are required. For instructions:
   !     https://devcenter.heroku.com/articles/go-support> expected:<> but was:< !     Godep, GB or govendor are required. For instructions:
   !     https://devcenter.heroku.com/articles/go-support>
  ASSERT:should install default Go version
  ASSERT:should recommend godep
  ASSERT:should install Virtualenv
  ASSERT:should install Mercurial
  ASSERT:should install Bazaar
  ASSERT:should run go get

  Ran 2 tests.

  FAILED (failures=10)
  3 SECONDS

  TEST SUITE: detect_test.sh
  testDetect_NotFound
  ASSERT:expected:<no> but was:<>
  testDetect_Go
  ASSERT:Expected captured exit code to be 0; was <1> expected:<0> but was:<1>
  ASSERT:expected:<Go> but was:<>

  Ran 2 tests.

  FAILED (failures=3)
  0 SECONDS

3 SECONDS

------
FAILURES (see individual results for details)
3 SECONDS
```

Thanks for your time and clarifications.

**Comment by freeformz** [comment]
I need to remove the test directroy as those tests aren't run. I currently use a set of internal integration tests.

**Comment by RochesterinNYC** [comment]
Reference: removed via https://github.com/heroku/heroku-buildpack-go/commit/80fa62172f00aeabe240f2bc9d05f94d68824e7a

@freeformz can I ask why those integration tests are internal? It'd be great to have those be open to the community as we'd be able to make pull requests with greater confidence after having checked them against the test suite.

**Comment by freeformz** [comment]
@RochesterinNYC They are internal because the testing framework is internal. I'll probably steal some stuff from the nodejs buildpack, which uses Docker and shunit and just start re-doing the tests as the buildpack is getting more complex these days.

**Comment by freeformz** [comment]
For clarity ... The buildpack should have a bunch of public unit tests as well as the internal integration tests.

**Comment by RochesterinNYC** [comment]
Oh okay, this is a different testing framework from https://github.com/heroku/heroku-buildpack-testrunner?

And I'm not sure what you mean by the public unit tests? Are they located somewhere in this repo?

**Comment by freeformz** [comment]
@RochesterinNYC _should_, meaning they need to be written.

**Comment by freeformz** [comment]
@RochesterinNYC Here is a start #123
