### ISSUE TITLE
Govendor fail when vendor/*/ is in .gitignore

### ISSUE THREAD

**Issue by plispe** [heroku/heroku-buildpack-go#126]
I would like to deploy go app to Heroku, but when I have vendor/*/ in .gitingore, deploy fails with following output 

remote: Building source: remote: 
remote: -----> Using set buildpack heroku/go 
remote: -----> Go app detected remote: -----> Checking vendor/vendor.json file. 
remote: -----> Installing go1.6.2... done 
remote: -----> Running: go install -v -tags heroku ./... 
remote: server.go:6:2: cannot find package "github.com/codegangsta/negroni" in any of: 
remote: /tmp/build_88aad1b6a1decb1dec2c48bf65972d02/.heroku/go/src/gitlab.beplus.io/bebroker/api/vendor/github.com/codegangsta/negroni (vendor tree)

according the govendor documentation **govendor sync** should be used to restore govendor dependencies.

> "If you ignore vendor/*/, restore dependencies with govendor sync"

I suppose, that the buildpack don't use govendor sync. Could you fix it please? Thank you.

**Comment by freeformz** [comment]
@plispe I've added this to master. If you `heroku buildpacks:set https://github.com/heroku/heroku-buildpack-go.git` can you try pushing again w/o anything except `vendor.json` in `vendor/` ? If everything goes okay I'll release it as v39 (and then you won't need to set a buildpack).

**Comment by plispe** [comment]
I tried your fix and it works like a charm 👍. Thank you very much.

**Comment by freeformz** [comment]
@plispe Released as v39 of the buildpack. In about ~30m you can change your buildpack back (`heroku buildpacks:set heroku/go`) and it should continue to work on next push.
