### ISSUE TITLE
GB support expects go file in src/ bug GB doesn't

### ISSUE THREAD

**Issue by jobi** [heroku/heroku-buildpack-go#128]
I'm just getting started with GB so I could be wrong, but if I understand correctly, GB now expects files to be put in subdirectories of `src/`, while the go buildpack looks for a go file in `src/`. I had to create a `src/dummy.go` file for the buildpack to recognize my project as being go / GB

**Comment by freeformz** [comment]
it looks for any .go files in src and it's sub directories: https://github.com/heroku/heroku-buildpack-go/blob/9d828217e58e6976ed1098c3d0980dc291a12b35/bin/detect#L8

The tests that I have for GB don't include a .go file in src, but in a sub directory: https://github.com/heroku/heroku-buildpack-go/tree/9d828217e58e6976ed1098c3d0980dc291a12b35/test/fixtures/gb-vendor/src

**Comment by freeformz** [comment]
Do you have the build output from the failed build?

**Comment by freeformz** [comment]
This was closed by 9b9ba7124c6f61eace947a7858e17351edc07e21
