### ISSUE TITLE
Buildpack not detected when using glide

### ISSUE THREAD

**Issue by FranzBusch** [heroku/heroku-buildpack-go#135]
Hi,

I created a new project and set the buildpack to heroku/go. Every time I deploy it says "failed to detect buildpack". I am using glide and locally everything builds and runs fine.

Here is the repository if you want to have look:
https://github.com/FranzBusch/myteamapi

**Comment by freeformz** [comment]
ATM you have to use the master branch as I haven't released it yet to `heroku/go`. You can use master by doing the following: `heroku buildpacks:set https://github.com/heroku/heroku-buildpack-go.git`.

**Comment by FranzBusch** [comment]
Ah, thank you :)

**Comment by freeformz** [comment]
This is now released, so you have `heroku buildpacks:set heroku/go` and it should work.
