### ISSUE TITLE
can't fetch dependencies

### ISSUE THREAD

**Issue by brunchybit** [heroku/heroku-buildpack-go#136]
I'm pretty sure this is me, but I'm wondering why I can't get my heroku build to succeed. I'm getting a stack trace that says the dependencies can't be found, as below: 

```
-----> Fetching set buildpack https://github.com/kr/heroku-buildpack-go.git... done
-----> Go app detected
-----> Checking Godeps/Godeps.json file.
-----> Installing go1.6... done
-----> Running: godep go install -tags heroku ./...
tufs.go:3:8: cannot find package "github.com/gin-gonic/gin" in any of:
    /app/tmp/cache/go1.6/go/src/github.com/gin-gonic/gin (from $GOROOT)
    /tmp/build_9e17705ddb9939294fda95a5c08dd8bf/.heroku/go/src/github.com/larquin/tufs/Godeps/_workspace/src/github.com/gin-gonic/gin (from $GOPATH)
    /tmp/build_9e17705ddb9939294fda95a5c08dd8bf/.heroku/go/src/github.com/gin-gonic/gin
godep: go exit status 1
 !     Push rejected, failed to compile Go app
```

Again this is probably something configuration wise that I'm missing, as I'm a noob, but any help would be appreciated.

**Comment by freeformz** [comment]
godep requires that `vendor/` be checked in. AFAICT from that output `vendor/` or at least parts of it aren't checked in. The buildpack also supports `govendor`, which doesn't have that requirement: https://github.com/kardianos/govendor/blob/master/doc/faq.md#q-how-do-i-prevent-vendor-source-from-being-checked-in

**Comment by freeformz** [comment]
See also: https://devcenter.heroku.com/articles/go-dependencies-via-govendor

**Comment by brunchybit** [comment]
Yup, you're absolutely right @freeformz I should have checked my `.gitignore` more carefully. Thanks for the response
