### ISSUE TITLE
Pushing apps with native Go vendoring doesn't seem to work

### ISSUE THREAD

**Issue by lpar** [heroku/heroku-buildpack-go#146]
According to [the documentation](http://docs.cloudfoundry.org/buildpacks/go/#pushing_Apps_with_native_Go_vendoring) you can use only native Go vendoring, as long as you specify the package name in the `manifest.yml` file.

In reality, this doesn't seem to be supported -- the buildpack tells me I have to use gb, glide, govendor or godep.

**Comment by freeformz** [comment]
That should probably be a bug filed against Cloud Foundry. I would like to support a "no tool" option, but that's not supported ATM. FWIW: Those tools write to the "native Go vendoring" folder, so I don't know why you wouldn't use one of them if you have deps to vendor. And in the case of govendor with a project w/o deps we leverage the vendor/vendor.json file for build configuration.
