### ISSUE TITLE
Source code as package content

### ISSUE THREAD

**Issue by diegossilveira** [heroku/heroku-buildpack-go#157]
After using `pkgr` with `heroku-buildpack-go` I noticed that all source code (*.go) and other files (that are just used on development time) were present on the final RPM. Is this the expected result? Is there some way to change this behavior, and package just the application binary, the vendor directory and the Procfile?

**Comment by freeformz** [comment]
What is pkgr ?

**Comment by diegossilveira** [comment]
Sorry about that. [Packager](https://github.com/crohr/pkgr) (pkgr) is a project based on Heroku buildpacks that helps you packaging and distributing your applications. Besides pkgr has its own singularities, I believe this "issue" is related to this buildpack. Do you deploy the go source code on heroku or just the resulting binaries?

**Comment by freeformz** [comment]
We deploy both as it's (a) more consistent with other build packs; (b) we
can't ensure what files the program would want to access during execution,
so only copying parts of the repo could be problematic (c) and with some
variables set you can also 'heroku run bash' and have a full, working go
environment.

**Comment by diegossilveira** [comment]
@freeformz, thanks for clarifying!
