### ISSUE TITLE
What if I want to install a third party main package?

### ISSUE THREAD

**Issue by ggaaooppeenngg** [heroku/heroku-buildpack-go#160]
I am using godep, I make config like this 

```
{
        "ImportPath": "github.com/ggaaooppeenngg/mypackage",
        "GoVersion": "go1.7",
        "GodepVersion": "v74",
        "Packages": [
            "./...",
            "github.com/other/package/..."
        ],
...
```

It runs `go install github.com/other/package/...`, report no package matches, I think this is because      that vendor directory is not a directory for go install to search, what I can do to add some main packages that I want use as a binary in my project?

**Comment by freeformz** [comment]
`godep save ./... github.com/other/package/...`, will save `./...` and `github.com/other/package/...` to vendor. But you need to run that command like that every time. I suggest using `govendor` instead and using `govendor fetch github.com/other/package` and then in `vendor/vendor.json` add a `heroku.install` array like described here: https://devcenter.heroku.com/articles/go-dependencies-via-govendor#build-configuration
