### ISSUE TITLE
Unable to set linker symbol

### ISSUE THREAD

**Issue by FZambia** [heroku/heroku-buildpack-go#164]
Hello, I am trying to set `$GO_LINKER_SYMBOL` to set version of application on build stage. 

Here is my [app.json](https://github.com/centrifugal/centrifugo/blob/master/app.json) file (I expect version to be default - SHA sum of commit: `$SOURCE_VERSION`) - looks like I do sth wrong as there is no version built in after deploy to Heroku (using `deploy to Heroku` button) but I can not understand how to fix it. 

Could you help me?

**Comment by freeformz** [comment]
What app is this? I'd like to take a look at the build output.

**Comment by freeformz** [comment]
PS: It's probably better to do this in a heroku ticket, than as an issue on the buildpack.

**Comment by FZambia** [comment]
Here is an app - https://github.com/centrifugal/centrifugo, there is a `deploy to Heroku` button in project README. I provided a link to its `app.json` file in issue description. My app is http://centrifugo.herokuapp.com - I have not found any helpful details in build log that was available to me while deploying.

**Comment by FZambia** [comment]
There is a line in BUILD log:

```
go install -v -tags heroku . 
```

So looks like I just set `GO_LINKER_SYMBOL ` env var in wrong way because build flags do not include `-ldflags` - i.e. [this](https://github.com/heroku/heroku-buildpack-go/blob/master/bin/compile#L334) branch not executed. But I just can't find my mistake:)

**Comment by freeformz** [comment]
Was this app deployed via a button (app.json)? I believe `$SOURCE_VERSION` isn't set during a push like this because we don't actually get the sha from github (or if we do get it doesn't make it through the pipeline properly).

**Comment by FZambia** [comment]
Yes, via button, you are right - I just added explicit `GO_LINKER_VALUE` and everything works now. Thanks a lot for your help - this is not ideal as I need to set version manually after clicking on `deploy to heroku` button now but solves a problem. And actually I already set a lot of other vars during build.

If you know where to open issue to fix pipeline (if its possible) - could you take over it? Looks like this issue can be closed.
