### ISSUE TITLE
How to deploy app without any dependencies

### ISSUE THREAD

**Issue by dabio** [heroku/heroku-buildpack-go#166]
This is not really an issue, but I'd like to know, how can I deploy go app without any dependency managers?

I tried a somewhat *hacky*workaround and bring my project into a gb-folder structure (src/**/*.go and vendor/src/). But is it possible without doing so?

**Comment by freeformz** [comment]
The recommended solution is to just drop a basic `vendor/vendor.json`. This allows you to add `heroku` section to [customize build time](https://devcenter.heroku.com/articles/go-dependencies-via-govendor#build-configuration) behavior as well.

**Comment by Xe** [comment]
@dabio #174 has documentation on how to do this.
