### ISSUE TITLE
Cannot deploy when using cache for go/glide/hg

### ISSUE THREAD

**Issue by Kay-Zee** [heroku/heroku-buildpack-go#167]
After release `v56`, I get this error:
```
-----> Using go1.7.4
-----> Using glide v0.12.3
-----> Using hg v3.9
 !     Push rejected, failed to compile Go app.
 !     Push failed
```
when deploying, on any heroku app that have already been previously deployed to. If I deploy a fresh app, I do not get this error, instead, I get
```
-----> Installing go1.7.4
-----> Fetching go1.7.4.linux-amd64.tar.gz... done
-----> Installing glide v0.12.3
-----> Fetching glide-v0.12.3-linux-amd64.tar.gz... done
-----> Installing hg 3.9
-----> Fetching mercurial-3.9.tar.gz... done
```
and then the build moves on. If I try to deploy again to the same app with a trivial change, it will error.

Is there an easy way to disable the go/glide/hg cache?

**Comment by freeformz** [comment]
Does the `fixGlide` branch solve the problem for you (it did for me)? You can test it by issuing:
`heroku buildpacks:set https://github.com/heroku/heroku-buildpack-go.git\#fixGlide` and then pushing again.

Thanks for the report and sorry this happened.

**Comment by jeromegn** [comment]
I had the same issue and using that branch fixed it, thanks @freeformz

**Comment by Kay-Zee** [comment]
That branch fixed it for me as well, thanks!

**Comment by freeformz** [comment]
This is released now, so you can set your buildpack back to the released `heroku/go` buildpack via `heroku buildpacks:set heroku/go` (assuming you are only using the Go buildpack.
