### ISSUE TITLE
Go get fails for private repos

### ISSUE THREAD

**Issue by eaigner** [heroku/heroku-buildpack-go#17]
The `go get ./...` stage obviously fails for private repos. Any idea how I could use a private repo with the buildpack?

**Comment by PeterSchuhmannNetflow** [comment]
In case anyone still has to figure out a way to make it work there is a heroku parameter to set the access token for private repos. Which you can find here in section "Private Git Repos" https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-go 

you basically have to set for your heroku repo the gitlab.com or github.com (whatever you use) domain + personal access token. In my case it was:
`heroku config:set GO_GIT_CRED__HTTPS__GITLAB__COM=<personal access token>`
my personal access token only had permissions "api read". 

worked like a charme for me
