### ISSUE TITLE
Is GB actually supported and how to use it with this Go buildpack?

### ISSUE THREAD

**Issue by andreycpp** [heroku/heroku-buildpack-go#176]
I'm having trouble using GB with Go buildpack. When I "git push heroku master" I'm getting "Failed to detect app matching buildpack" error (see below).

According to https://devcenter.heroku.com/articles/go-support#supported-dependency-vendor-managers, Heroku Go buildpack should do this check:

"3. has a src directory, which has sub directories, contains one or more .go files, identifying the application as being managed by gb."

Here's my project layout (omitting git files):

$ tree -a
.
├── .git
└── src
    └──── hello
        ├────── Procfile
        └────── main.go

$ git ls-files
src/hello/Procfile
src/hello/main.go

Here's what I'm getting - please advice what am I doing wrong or whether it's a bug:

$ heroku create
Creating app... done, ⬢ murmuring-hollows-29547
https://murmuring-hollows-29547.herokuapp.com/ | https://git.heroku.com/murmuring-hollows-29547.git

$ heroku buildpacks:set heroku/go
Buildpack set. Next release on murmuring-hollows-29547 will use heroku/go.
Run git push heroku master to create a new release using this buildpack.

$ git push heroku master
Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (6/6), 580 bytes | 0 bytes/s, done.
Total 6 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Failed to detect app matching https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/go.tgz buildpack
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to murmuring-hollows-29547.
remote:

**Comment by freeformz** [comment]
Sorry, I just saw this. Not sure what's up with my notifications. :-( 

This should be working, with the exception that the Procfile is in the wrong place, but that shouldn't affect detection.

Given this structure (.git filtered out):
```console
$ tree -a -I .git
.
├── .gitignore
├── Procfile
└── src
    └── hello
        └── main.go

2 directories, 3 files
```

A `heroku create` and `git push heroku master` does the following:
```console
$ heroku create
Creating app... done, ⬢ nameless-sands-71006
https://nameless-sands-71006.herokuapp.com/ | https://git.heroku.com/nameless-sands-71006.git

$ git push heroku master
Counting objects: 7, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (7/7), 611 bytes | 0 bytes/s, done.
Total 7 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Go app detected
remote: -----> Fetching jq... done
remote:  !!
remote:  !!    'GOVERSION' isn't set, defaulting to 'go1.8'
remote:  !!
remote:  !!    Run 'heroku config:set GOVERSION=goX.Y' to set the Go version to use
remote:  !!    for future builds
remote:  !!
remote: -----> Installing go1.8
remote: -----> Fetching go1.8.linux-amd64.tar.gz... done
remote: -----> Fetching errors-0.8.0.tar.gz... done
remote: -----> Fetching gb-0.4.4-pre.tar.gz... done
remote: -----> Installing GB v0.4.4-pre... done
remote: -----> Running: gb build -tags heroku
remote: hello
remote: -----> Post Compile Cleanup
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 1.9M
remote: -----> Launching...
remote:        Released v3
remote:        https://nameless-sands-71006.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/nameless-sands-71006.git
 * [new branch]      master -> master
```

`main.go` looks like this:
```go
package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
)

func main() {
	port := os.Getenv("PORT")
	fmt.Println("Listening on", port)
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		io.WriteString(w, "Hello")
	})
	http.ListenAndServe(":"+port, nil)
}
```

and the `Procfile` looks like this:
```
web: bin/hello

```

**Comment by KingRider** [comment]
@freeformz not work, a problem the version GO from heroku.

**Comment by freeformz** [comment]
@KingRider Please open a support ticket on Heroku or provide more information here, preferably including the build output.
