### ISSUE TITLE
goose cannot be imported, via govendor

### ISSUE THREAD

**Issue by salismt** [heroku/heroku-buildpack-go#179]
when I import goose, I got the following error
import "bitbucket.org/liamstask/goose/cmd/goose" is a program, not an importable package

How do I add goose and have goose command enable in my heroku instance?
I have read this "https://bitbucket.org/liamstask/goose/issues/55/heroku-instructions-no-longer-works-on-go"
but it's not compiling

**Comment by beydogan** [comment]
@salismt have you fixed this? I'm having the same issue.

**Comment by freeformz** [comment]
My approach would be to do the following (I haven't tested, but that should work.):

```terminal
$ govendor fetch bitbucket.org/liamstask/goose/cmd/goos
```

Then edit vendor.json and add `bitbucket.org/liamstask/goose/cmd/goos` to the `heroku.install` line.

Please re-open if this is still an issue and the above doesn't work.
