### ISSUE TITLE
Update to latest Go release 1.8.3

### ISSUE THREAD

**Issue by djui** [heroku/heroku-buildpack-go#186]
https://groups.google.com/forum/#!topic/golang-nuts/oUOV9PFq_8s

Times are moving fast...

**Comment by Xe** [comment]
Closed in https://github.com/heroku/heroku-buildpack-go/pull/185 commit https://github.com/heroku/heroku-buildpack-go/commit/19adaf46fc05fe806f28dbbf77f024b7be6ee142
