### ISSUE TITLE
remote: can't load package

### ISSUE THREAD

**Issue by connelevalsam** [heroku/heroku-buildpack-go#195]
Terminal output:
`remote: -----> Fetching any unsaved dependencies (glide install)
remote: [INFO]	No dependencies found. Nothing installed.
remote: [INFO]	Setting references.
remote: [INFO]	No references set.
remote: [INFO]	Exporting resolved dependencies...
remote: [INFO]	Replacing existing vendor dependencies
remote: -----> Running: go install -v -tags heroku . 
remote: can't load package: package github.com/connelevalsam/GoWebDev/GoLearning/herokuDeploys/cb01simpleMapCrud: no buildable Go source files in /tmp/tmp.UGXhlMupcp/.go/src/github.com/connelevalsam/GoWebDev/GoLearning/herokuDeploys/cb01simpleMapCrud
remote:  !     Push rejected, failed to compile Go app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to fatidique-moliere-33099.
remote: 
`
my code dir:
`cb01simpleMapCrud
    ├── assets
    │   ├── css
    │   │   └── tachyons.css
    │   └── img
    │       └── bg1.jpg
    ├── glide.lock
    ├── glide.yaml
    ├── Procfile
    ├── src
    │   └── main
    │       └── main.go
    ├── templates
    │   ├── admin
    │   │   ├── create.html
    │   │   ├── delete.html
    │   │   ├── index.html
    │   │   ├── read.html
    │   │   └── update.html
    │   ├── index.html
    │   └── login.html
    └── vendor

9 directories, 13 files
`
I don't know what to do to deploy to heroku

**Comment by freeformz** [comment]
Can I get access to the source to try to duplicate and suggest a PR?

**Comment by freeformz** [comment]
Closing since I couldn't get access to the source code / app.
