### ISSUE TITLE
S3 bucket prevents easy contribution

### ISSUE THREAD

**Issue by kyleconroy** [heroku/heroku-buildpack-go#197]
I'm working on [adding support for dep](https://github.com/heroku/heroku-buildpack-go/pull/196) to the buildpack. I need to pull down two new binaries, dep and [tomlq](https://github.com/kyleconroy/tomlq). I've added them to the `files.json`, but the `sync-files` command requires access and auth keys to a private Heroku S3 bucket.

We should change the buildpack to accept an environment variable (HEROKU_GO_S3_BUCKET) to configure the bucket and aid contribution.

**Comment by freeformz** [comment]
What I'd like to do is to figure out a way to pass a something like a `HEROKU_GO_FILES_LOCATION` env var that could also be a `files:///` url so that when running the tests the files would be "downloaded" from the local file cache instead. This could then also be used for hosting your own set of binaries in the S3 bucket (or other location) of your choice.

**Comment by freeformz** [comment]
Master now uses a `file://` url and files in `test/assets`, which is populated with the files in `[data.json](https://github.com/heroku/heroku-buildpack-go/blob/8fe505ee4193bb30520567c4add9fdcd50a756d1/data.json#L61)`'s `test.assets` array (references the files in `files.json`) by the `[bin/fetch-test-assets`](https://github.com/heroku/heroku-buildpack-go/blob/8fe505ee4193bb30520567c4add9fdcd50a756d1/bin/fetch-test-assets)` script.

This should allow mostly local testing. There are still cases though where dep/govendor/glide or others may fetch things from the internet. But the buildpack itself will use the `file:///` URL, except when using a devel version of go (the buildpack then fetches go from github and checks out the specified SHA; there is a test for this).

**Comment by freeformz** [comment]
PS: tests are also faster because of this as the test don't download the same version of Go over and over again for each test.
