### ISSUE TITLE
Add dep package management 

### ISSUE THREAD

**Issue by bscott** [heroku/heroku-buildpack-go#198]
The Go team recently added dep as a runner up for the Official package management tool, be nice to add it. 

https://github.com/golang/dep

**Comment by bscott** [comment]
PR #196 already in progress

**Comment by freeformz** [comment]
Done and in master, but not yet released on Heroku. Until it's released (a few weeks) it's usable by pinning the buildpack to the master branch vs. the released `heroku/go` version.

Thanks!
