### ISSUE TITLE
Go 1.9 is the default version, but gives unsupported warning

### ISSUE THREAD

**Issue by jmorrell** [heroku/heroku-buildpack-go#205]
With https://github.com/heroku/heroku-buildpack-go/pull/204 1.9 is now the default version of Go, but if you specify 1.9 you receive an unsupported error:

```
-----> Checking Godeps/Godeps.json file.
 !!    
 !!    Deprecated or unsupported version of go (go1.9)
 !!    See https://devcenter.heroku.com/articles/go-support#go-versions for supported version information.
 !!    
-----> Using go1.9
 !!    Installing package '.' (default)
 !!    
```

**Comment by freeformz** [comment]
#204 didn't [default](https://github.com/heroku/heroku-buildpack-go/blob/master/data.json#L4) to go 1.9, but it did make it available, but it's still unsupported. This will change this week though.

**Comment by freeformz** [comment]
Closing since it's now supported.
