### ISSUE TITLE
Deprecated or unsupported version of go (1.9.2)

### ISSUE THREAD

**Issue by freddiewanah** [heroku/heroku-buildpack-go#222]
Hey, I was trying to deploy the app with dep. And no matter what version I entered in the config file, it keeps giving me this bugs and denied me from pushing.

remote: -----> Go app detected
remote: -----> Fetching tq... done
remote:  !!
remote:  !!    Deprecated or unsupported version of go (1.9.2)
remote:  !!    See https://devcenter.heroku.com/articles/go-support#go-versions for supported version information.
remote:  !!
remote: -----> Installing 1.9.2
remote: -----> Fetching 1.9.2.linux-amd64.tar.gz...
remote: gzip: stdin: not in gzip format
remote: tar: Child returned status 1
remote: tar: Error is not recoverable: exiting now
remote:  !     Push rejected, failed to compile Go app.
remote:
remote:  !     Push failed

This is how I set up in Gopkg.toml
> [metadata.heroku]
  root-package = "github.com/heroku/go-getting-started"
  go-version = "1.9.2"
  install = [ "./..." ]

**Comment by johnsudaar** [comment]
You made a typo on your `go-version` it should be:

```
 go-version = "go1.9.2"
```

**Comment by freeformz** [comment]
Going to close this since the above comment is the answer.
