### ISSUE TITLE
Support Go 1.9.3

### ISSUE THREAD

**Issue by kevinburke** [heroku/heroku-buildpack-go#228]
Go 1.9.3 was released yesterday has several fixes for the compiler and runtime, listed here: https://github.com/golang/go/issues?q=milestone%3AGo1.9.3

It would be great if it was available for running Heroku Go apps.

**Comment by alexfalkowski** [comment]
It has been released!

**Comment by danp** [comment]
This was done in https://github.com/heroku/heroku-buildpack-go/pull/229.
