### ISSUE TITLE
Unable to set linker symbol

### ISSUE THREAD

**Issue by Tri125** [heroku/heroku-buildpack-go#232]
This is my [app.json](https://github.com/Tri125/HoP/blob/master/app.json). I'm deploying directly by pushing from git but it seems that ``$SOURCE_VERSION`` is not being set. It just runs ``Running: go install -v -tags heroku .``

Also, would it be possible to have it set to the latest tag instead of the commit sha1?

**Comment by freeformz** [comment]
Unfortunately `git push heroku master` doesn't consider app.json in any way.

You need to run `heroku config:set GO_LINKER_SYMBOL=main.version` for the app in question before you push.

Please let me know if that doesn't work.

**Comment by freeformz** [comment]
Closing since I haven't heard back. Please re-open if the config changes did not solve your issue. Thx.
