### ISSUE TITLE
Allow to set up LD_LIBRARY_PATH in build's local env

### ISSUE THREAD

**Issue by ssnickolay** [heroku/heroku-buildpack-go#247]
Some Golang packages use `LD_LIBRARY_PATH` for compiling C bindings (in my case it is [gocv](https://github.com/hybridgroup/gocv/blob/master/env.sh#L24)). 
So, can we add `LD_LIBRARY_PATH` to [loadEnvDir()](https://github.com/heroku/heroku-buildpack-go/blob/master/lib/common.sh#L163) for a possibility to set up its by custom heroku buildpacks?
I can do PR If there are no objections to this improvement.

**Comment by freeformz** [comment]
Send a PR so it can be reviewed. Thanks!
