### ISSUE TITLE
Update migrate repo URL

### ISSUE THREAD

**Issue by intel352** [heroku/heroku-buildpack-go#250]
The `migrate` tool has a new repo URL: https://github.com/golang-migrate/migrate
Also the version is now 3.2.0. I didn't see the version hard-coded, just calling that out in case you want to also update the readme to be accurate.

**Comment by freeformz** [comment]
Master now has support for golang-migrate @v3.4.0 (and the older mattes migrate version as well).

Do you think I/we should PR/upload the other versions just to be complete?

**Comment by freeformz** [comment]
v91 of `heroku/go` is released with support for golang-migrate v3.4.0.

**Comment by danp** [comment]
Fixed by https://github.com/heroku/heroku-buildpack-go/pull/264.
