### ISSUE TITLE
heroku-buildpack-go doesn't detect Go projects

### ISSUE THREAD

**Issue by NatoBoram** [heroku/heroku-buildpack-go#253]
```
Status: Downloaded newer image for gliderlabs/herokuish:latest
       -----> Fetching custom buildpack
       -----> Unable to select a buildpack
ERROR: Job failed: exit code 1
```

Project : https://gitlab.com/NatoBoram/Go-Miiko/

What are the full requirements for `heroku-buildpack-go` to detect a Go project? Is there a way to tell it that I'm using Go, and that `go build` actually works?

**Comment by freeformz** [comment]
The buildpack readme states

![screen shot 2018-06-29 at 2 52 06 pm](https://user-images.githubusercontent.com/103/42116430-084920cc-7bac-11e8-9117-3691444eefa6.png)

**Comment by freeformz** [comment]
There is also another section of the readme for non conforming projects: https://github.com/heroku/heroku-buildpack-go#usage-with-other-vendoring-systems

**Comment by freeformz** [comment]
My suggestion is to use one of the tools listed in the readme to vendor your dependencies (or at least record them). Once that is done then this buildpack should work w/o problem and compile your application
