### ISSUE TITLE
heroku deploy can't find metadata.heroku in Gopkg.toml

### ISSUE THREAD

**Issue by prhineh1** [heroku/heroku-buildpack-go#254]
I've followed the instructions for deploying a Golang app using dep to Heroku. However, when running 'git push heroku master', I get the following error, "The 'metadata.heroku["root-package"]' field is not specified in 'Gopkg.toml'." Except it is there: https://github.com/prhineh1/Go-site/blob/heroku-build/Gopkg.toml (line 27).

I followed the directions in the readme. What am I missing here?

**Comment by alindeman** [comment]
Since your code is only on the `heroku-build` branch, and not yet `master`, could you make sure you're pushing that branch to Heroku? The command would be `git push heroku heroku-build:master`. Is that the command you're running?

**Comment by prhineh1** [comment]
Thank you, alindeman, that worked.
