### ISSUE TITLE
Go modules on Heroku CI

### ISSUE THREAD

**Issue by larryfox** [heroku/heroku-buildpack-go#270]
Hi, is there a plan to support Go modules on Heroku CI?

Seems like it should work similar to the `dep|glide|godep` tools, just without the `grep -v /vendor/` stuff.

https://github.com/heroku/heroku-buildpack-go/blob/3254d7ba568b8142ca22f0891f9e7a68cec1c31b/bin/test#L48-L57

**Comment by dhax** [comment]
currently without a vendor folder my Procfile is ignored resulting in "Procfile declares types -> (none)" and no Dyno attached. Running go build --mod=vendor locally and committing my vendor folder, then web process in Procfile gets started. Should it also work without vendoring dependencies before pushing to heroku?

**Comment by freeformz** [comment]
Now part of v100.
