### ISSUE TITLE
App not compatible with buildpack error

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [heroku/heroku-buildpack-go#271]
```aks:ride-companion-api$ git push heroku master -f
Counting objects: 69, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (69/69), done.
Writing objects: 100% (69/69), 10.53 KiB | 2.11 MiB/s, done.
Total 69 (delta 25), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/go.tgz
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to ride-companion-api.
remote: 
To https://git.heroku.com/ride-companion-api.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/ride-companion-api.git'
```

I cloned the default app, copied the relevant files but this is the error I get. What file is missing any idea?

**Comment by freeformz** [comment]
Which default app? The one in the getting started guide? Also, when you say "copied the relevant files" what do you mean?

PS: If you open a support ticket with Heroku they can probably help or escalate it internally and get better help.

**Comment by ankitsinghaniyaz** [comment]
I got the default scaffold which Heroku provided and copied all the files to my existing project. It looks like I had missed some of the files. I tried again and it works. Thanks for the help.

**Comment by GuruJustin** [comment]
Hello there.

I have these errors.

remote: -----> Build succeeded!
remote: -----> ngrok app detected
remote: -----> Installing ngrok...  done
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/java.tgz
remote:        Could not find a pom.xml file! Please check that it exists and is committed to Git.
remote:
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to trivia-multi.
remote:
To https://git.heroku.com/trivia-multi.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/trivia-multi.git'

Somebody helps me.

**Comment by edmorley** [comment]
@GuruJustin Hi! Your error is not related to either the Go buildpack, or the issue the original reporter had above. Support issues (rather than bugs) are best reported at https://help.heroku.com . Also in general it's best practice to create new issues (for bugs) on a GitHub repo if there isn't a recent + definitely related existing issue, rather than commenting on much older issues. Hope you get your app working! :-)
