### ISSUE TITLE
Updating default go1.10 minor version breaks go app builds

### ISSUE THREAD

**Issue by yomikaze** [heroku/heroku-buildpack-go#274]
#273 

```-----> Go app detected
-----> Installing go1.10.5
-----> Fetching go1.10.5.linux-amd64.tar.gz... 
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
 !     Push rejected, failed to compile Go app.
 !     Push failed```

**Comment by bigshahan** [comment]
Getting the same exact error too.

**Comment by shauryachats** [comment]
Yep, same error. 
Might be Heroku's problem, not ours.

https://stackoverflow.com/questions/11543541/heroku-push-gzip-stdin-not-in-gzip-format

**Comment by bigshahan** [comment]
@shauryachats  That stackoverflow reference is really old, and this only started happening with the latest minor version change.

**Comment by freeformz** [comment]
Sorry about that. There was a mistake during the deploy: https://status.heroku.com/incidents/1660

This is resolved and we'll be opening some follow up items to help ensure that it doesn't happen again by accident.
