### ISSUE TITLE
Caching build artifacts?

### ISSUE THREAD

**Issue by treystout** [heroku/heroku-buildpack-go#276]
I'm using the build pack to compile a binary API that has over 40 go dependencies, each push seems to do `got get` every dependency on every build. Is caching of $GOPATH between builds an option? Is there something I need to configure?

**Comment by freeformz** [comment]
What dependency tool are you using?

**Comment by freeformz** [comment]
If you open a support ticket, include the app name, and grant access to the app I can get a bunch more info w/o having to ask you here.

**Comment by treystout** [comment]
Sorry I missed this had email notifications turned off. I'm using go 1.11's new built-in module support. go.mod/go.sum (which should be putting gotten deps in the $GOPATH I think). When you say open a support ticket do you mean in heroku itself?

**Comment by freeformz** [comment]
Yes. Caching should work, but I don't recall (of the top of my head) if it's well tested.

**Comment by edwardmp** [comment]
Hi @freeformz, we are using the buildpack in combination with Go modules as well, but caching doesn't seem to work. We are using Go version 1.11.5.

**Comment by freeformz** [comment]
@edwardmp Can you open a support ticket, detail what isn't happening, provide access to the application, and ask them to assign the ticket to me?

I can use the build logs and some internal tools to look at the BUILD cache (which should contain Go's cache) to see what is going on.

Thanks!
