### ISSUE TITLE
/bin/herokuish buildpack test doesn't use GO_GIT_CRED

### ISSUE THREAD

**Issue by purplesmoke05** [heroku/heroku-buildpack-go#282]
I found that we cannot use heroku-buildpack-go with GO_GIT_CRED__{protocol}__{host}
in GITLAB Auto Devops.
How can we use?

**Comment by freeformz** [comment]
I don't know anything about GITLAB Auto Devops or how the buildpack relates to it.

Can you provide details on how to re-create the failure that I can try?

**Comment by freeformz** [comment]
@airking05 AFAICT the current versions of herokuish pass the required [env directory](https://github.com/gliderlabs/herokuish/blob/8821a8b6f5c8be439b8138f533c6110d1eaeb918/include/buildpack.bash#L181) to the buildpack, which is all that is [required from what is executing the buildpack](https://github.com/heroku/heroku-buildpack-go/blob/94401f162c54f2d5245da27b204c6bfdc623b007/test/run#L150).

**Comment by freeformz** [comment]
Can you try it with the `gitlab` branch that is part of #288 ?

**Comment by freeformz** [comment]
I believe this is fixed now.
