### ISSUE TITLE
Using Godep doesn't install binaries from other libraries

### ISSUE THREAD

**Issue by shaunduncan** [heroku/heroku-buildpack-go#29]
Not really sure if this this is a buildpack issue, a godep issue, or even an issue at all, but if I have a dependency that is expected to create a binary to use, `godep go get` doesn't move artifacts from `bin` in the sandbox path it uses for each dependency. Perhaps that's intended, but I'm not sure. This is what I have as a custom workaround: https://gist.github.com/shaunduncan/6904322

Again, I'm just curious if this is intended or not :)

Thanks!

**Comment by kevinburkeshyp** [comment]
Any update/decision here?

**Comment by kevinburkeshyp** [comment]
FWIW, when I try running that script, I get `getwd: no such file or directory`, though not sure which file/dir is being referenced.

**Comment by kevinburkeshyp** [comment]
Ended up resolving this by adding a dummy file with all of the dependencies imported.

**Comment by freeformz** [comment]
Can anyone produce an example for this? I can't seem to duplicate any of the bin behavior that this script would use or find a dependency that creates a binary during normal `godep go install ./...`.  Possibly missing something?
