### ISSUE TITLE
Cannot build using go1.12 and modules

### ISSUE THREAD

**Issue by m90** [heroku/heroku-buildpack-go#297]
I was trying to upgrade an existing app using Go modules from Go 1.11 to Go 1.12.

The updated `go.mod` looks like

```
// +heroku goVersion go1.12
// +heroku install ./cmd/...

module github.com/m90/taell-go

require (
```

Which from reading this: https://github.com/heroku/heroku-buildpack-go/blob/874d100cae8814e7424b3e4aefca5c706ca61a58/data.json#L3 should be supported.

Yet the build will fail with the following:

```
-----> Deleting 2 files matching .slugignore patterns.
-----> Go app detected
 !!    
 !!    Go modules are an experimental feature of go1.11+
 !!    Any issues building code that uses Go modules should be
 !!    reported via: https://github.com/heroku/heroku-buildpack-go/issues
 !!    
 !!    Additional documentation for using Go modules with this buildpack
 !!    can be found here: https://github.com/heroku/heroku-buildpack-go#go-module-specifics
 !!    
 !!    You are using go1.12, which does not support the Go modules experiment
 !!    
 !!    These go versions support Go modules: go1.11, go1.11.1, go1.11.2, go1.11.3, go1.11.4, go1.11.5, go1.11beta2, go1.11beta3, go1.11rc1, go1.11rc2, go1.12beta1, go1.12beta2, go1.12rc1
 !!    
 !!    Please add a comment in your go.mod file, or update an existing one, to specify a Go version that does like so:
 !!    // +heroku goVersion go1.11.5
 !!    
 !!    Then commit and push again.
 !     Push rejected, failed to compile Go app.
 !     Push failed
```

which I also don't fully understand as the version also mentioned here: https://github.com/heroku/heroku-buildpack-go/blob/874d100cae8814e7424b3e4aefca5c706ca61a58/data.json#L48

**Comment by m90** [comment]
Interestingly, it looks like current master is correct:

```
➜  heroku-buildpack-go git:(master) cat data.json | jq  -e '.Go.SupportsModuleExperiment | any(. == "'go1.12'")' 
true
➜  heroku-buildpack-go git:(master) cat data.json | jq -c -r -M '.Go.SupportsModuleExperiment | sort | join(", ")'
go1.11, go1.11.1, go1.11.2, go1.11.3, go1.11.4, go1.11.5, go1.11beta2, go1.11beta3, go1.11rc1, go1.11rc2, go1.12, go1.12beta1, go1.12beta2, go1.12rc1
```

so the platform seems to be building against an outdated buildpack. How can I update this?

**Comment by sowjumn** [comment]
Thank you for letting us know. We will look into this ASAP.

**Comment by sowjumn** [comment]
go1.12 is now available.

**Comment by m90** [comment]
Great, thank you for resolving this so quickly. My app has already re-built using 1.12 :tada:

One question for future upgrades remains: The docs at https://devcenter.heroku.com/articles/go-support#go-versions currently refer to the `master` branch of this repository when it comes to supported versions. Can I assume that when a new Go version is added to the buildpack and merged to master, I can safely use it? Or do you need to release this in some way before?

**Comment by freeformz** [comment]
Thanks for releasing @sowjumn!

**Comment by jmorrell** [comment]
@m90 to answer your question: You can point directly to the master branch of the buildpack (or another branch) if necessary, but the official `heroku/go` buildpack image needs to be released in a separate process.

Usually this is quick, but some things got shuffled in this case.
