### ISSUE TITLE
Defaults to v1.11.x version, despite "go 1.12" in go.mod file

### ISSUE THREAD

**Issue by msiebuhr** [heroku/heroku-buildpack-go#301]
When building, I get this message:

```
 !!    The go.mod file for this project does not specify a Go version
 !!    
 !!    Defaulting to go1.11.5
 !!    
 !!    For more details see: https://devcenter.heroku.com/articles/go-apps-with-modules#build-configuration
 !!    
```

Despite `go.mod` having the line `go 1.12` in it.

Having to specify the same thing twice is a little weird to me.

**Comment by freeformz** [comment]
Our support for go modules predates the go tooling adding the `go X.Y` directive.

ATM, you will need to add a line like the following to get go1.12:
```
// +heroku goVersion go1.12
```

**Comment by jmorrell** [comment]
We are working to get support for the go version directive out soon

**Comment by jparcus34** [comment]
If who's you see me feel this now if you don't than you dround potna

**Comment by jparcus34** [comment]
Yeah

**Comment by freeformz** [comment]
A discussion on [go-nuts started by @sowjumn](https://groups.google.com/d/msg/golang-nuts/n6f-lbluk4A/Xwb3QfT5CgAJ) indicates that the `go` directive in the go.mod file shouldn't be used for version selection. It's meant to indicate the version of the language **features** that are required by the code base. For example, if a breaking change were introduced in go1.13 a `go 1.12` directive would **in theory** allow for the code base to be compiled with go1.13, but using go1.12's feature set. I'm unsure how the language maintainers are going to pull this off over time given each new version with incompatible changes adds to their maintenance complexity. Maybe they'll only support the previous version (`go 1.12` when go1.13 comes out, then only `go 1.13` when go1.14 comes out, etc)?

(cc @ianlancetaylor to validate my interpretation of his post)

So, given that, I'm not convinced that using the `go` directive in go.mod is a good idea, except for selecting the minimal major version to use when no other info is available.

Example: go1.13.1 is out and is the current default version we're using and the buildpack is used to compile code with a `go 1.12` directive. We have two options:
1. Trust that go1.13.1 will DTRT and properly compile the code base with the go 1.12 features
1. Use the latest minor version of go1.12

The later seems safer to me. The former is the intended use case, at least as I understand what was written.

**Comment by ianlancetaylor** [comment]
Yes: the "go" directive in go.mod indicates the language version to use when compiling code.  There is a lot more detail about how this is intended to work at golang/go#28221.

We will support all previous language versions.  It's not as hard as you suggest.  C and C++ compilers do this routinely, via command line options like GCC's `-std=`.

**Comment by freeformz** [comment]
So the `go` directive in the `go.mod` file is not for go version selection.

**Comment by msiebuhr** [comment]
I see. I'd still posit that having `go 1.12` in the file should make the buildpack should definitely not pick Go 1.11.5.

The right solution would then be to run any Go >= 1.12  w. `-lang=go1.12`.

**Comment by edmorley** [comment]
> I'd still posit that having `go 1.12` in the file should make the buildpack should definitely not pick Go 1.11.5.
> 
> The right solution would then be to run any Go >= 1.12 w. `-lang=go1.12`

I've filed #378 for discussing this further.

**Comment by tomandersen** [comment]
Ran into this today, so it's still happening. I used the GOVERSION env variable set to 1.14.2 to get my app running.  

Maybe the Heroku docs can make more of deal about setting GOVERSION in the env?

**Comment by axetroy** [comment]
I also got this issue

I found it has been closed, can someone tell me how to solve this?

**Comment by tomandersen** [comment]
Axetroy - In your Heroku app dashboard, go to settings, "Reveal Config Vars" then add one 

GOVERSION with value 1.14.2 or whatever you need. 
<img width="866" alt="Screen Shot 2020-05-22 at 8 19 48 AM" src="https://user-images.githubusercontent.com/221405/82667015-0754f800-9c05-11ea-982d-0d84ac8393b6.png">

**Comment by axetroy** [comment]
@tomandersen I did n’t read your last comment carefully before I sent the comment, anyway, thank you ❤️
