### ISSUE TITLE
v105 breaks root-level package installation if cmd dir exists

### ISSUE THREAD

**Issue by fgblomqvist** [heroku/heroku-buildpack-go#308]
PR #304 broke the installation of root-level packages if a `cmd` directory exists. Unless I've missed something, `cmd` is not an officially reserved directory name for go modules/packages. The only reference to it I was able to find was in the **unofficial** guide: https://github.com/golang-standards/project-layout#go-directories

While I can appreciate that layout, it is not official and therefore I think it's incorrect to push a breaking update, at least without any notice (e.g. there could have been an echo in the script saying something like "AS OF v105, ROOT LEVEL PACKAGES WILL NOT BE INSTALLED IF A cmd DIRECTORY EXISTS, PLEASE SEE <url> FOR MORE INFO").

One have to keep in mind that there might be older/bigger applications that happen to have a cmd package, but that still utilizes the root package as the main one (e.g. the one to build a binary from). Such is the case for me at the moment. Took a bit of debugging to figure out why the main binary stopped building all of a sudden (the cryptic "detected cmd directory" comment didn't help much).

Nonetheless, I followed the instructions that I saw somewhere that said to add the following comment to the go.mod: `// +heroku install ./...`. That restored the behavior.

Anyway, if you're planning on keeping this change as-is, a more clear notice should be added to the script (towards the top) imo.

**Comment by freeformz** [comment]
Thanks for your feedback and sorry this was a breaking change for you.

Putting main packages in `./cmd` is a common idiom for repositories that either contain multiple main packages or where the developer expects there to be multiple main packages in the future.

What do you think about the following behavior, assuming no `// +heroku install` directive?

1. If there is a main package in the root of the repo, set the package spec to `.`;
1. If there is no main package in `.`, and `./cmd` contains one or more sub directories, that *contain* main packages, then set the package spec to `./cmd/...`.
1. If neither are true, then default to `.`.

PS: If your code's only main package is in the root of your repo I suggest specifying `.` instead of `./...` via:
```
// +heroku install .
```

**Comment by fgblomqvist** [comment]
The suggested behavior sounds logical to me (and better than the current new one) :+1: 
The important part is definitely num. 1, to preserve the backwards compatibility.

**Comment by freeformz** [comment]
I've been playing around with another option...

If the buildpack were to run the following in the root of the code base, it would get a list of every main package in the repo:
```
go list -find -mod=vendor -f '{{ if eq .Name "main" }} {{.ImportPath}} {{ end }}' ./...
```

Install those.

This seems to DTRT in all the cases I can think of atm, except for some places where the buildpack already has special handling.

The only corner case I can think of right now where this may fail is when a repo has invalid go files somewhere in the repo (will cause go list to error). If those files normally aren't compiled then this wouldn't cause an error right now, but it would in this case.

**Comment by freeformz** [comment]
I have that working. Output of `make FIXTURE="mod-cmd" compile` locally looks like...

```console
-----> 
       Detected go modules via go.mod
-----> 
       Detected Module Name: github.com/heroku/fixture
-----> 
 !!    The go.mod file for this project does not specify a Go version
 !!    
 !!    Defaulting to go1.12.1
 !!    
 !!    For more details see: https://devcenter.heroku.com/articles/go-apps-with-modules#build-configuration
 !!    
-----> Installing go1.12.1
-----> Fetching go1.12.1.linux-amd64.tar.gz... done
-----> Determining packages to install
       
       Detected the following main packages to install:
         github.com/heroku/fixture/cmd/fixture
         github.com/heroku/fixture/cmd/other
       
----->Running: go install -v -tags heroku github.com/heroku/fixture/cmd/fixture github.com/heroku/fixture/cmd/other 
github.com/heroku/fixture/cmd/fixture
github.com/heroku/fixture/cmd/other

Compiled the following binaries:
       ./bin/fixture
       ./bin/other
```

I have a few things to clean up before opening a PR. Hopefully later tonight.

**Comment by fgblomqvist** [comment]
That looks like a beautiful solution, gj!

**Comment by freeformz** [comment]
@fgblomqvist I am running "slow" on this, but it's progressing.

**Comment by fgblomqvist** [comment]
No worries, since we could use the +heroku option (albeit not the prettiest,) we're not in a bad spot atm. But still, I do appreciate you putting in the work, thanks for that.
