### ISSUE TITLE
Quoted module in go.mod brakes default Procfile

### ISSUE THREAD

**Issue by jamesward** [heroku/heroku-buildpack-go#315]
My `go.mod` had:
```
module "github.com/jamesward/hello-go"
```
And the generated `Procfile` had:
```
web: hello-go"
```
(with the trailing double-quote)

It seems that quoting the module was something that should be fine.  In which case it should work ok with the generated `Procfile`.

**Comment by freeformz** [comment]
Doh. Time for another test. Thanks for reporting this.

**Comment by freeformz** [comment]
PS: As per the [devcenter docs](https://devcenter.heroku.com/articles/getting-started-with-go#push-local-changes) I suggest running `go mod tidy && go mod vendor` before `git commit` and pushing code to heroku. This ensures that `go.mod`, `go.sum`, & the contents of `vendor/` reflect the current code base. This **also**, at least with go1.12.1 (I've only tested this on that version so far) removes the quotes from `go.mod`.  Was this `go.mod` file handmade?

**Comment by jamesward** [comment]
Thanks!  Yeah, handmade and I'd seen the quotes somewhere.  Appreciate the prompt response and fix!
