### ISSUE TITLE
godep failing to install dependencies

### ISSUE THREAD

**Issue by shaunduncan** [heroku/heroku-buildpack-go#33]
I've been receiving an error today when performing a `git push heroku master`:

```
-----> Running: godep go install -tags heroku ./...
# cd /tmp/godep/repo/code.google.com/p/go.net; hg init
godep: create repo: fork/exec /app/tmp/cache/venv/bin/hg: no such file or directory
```

Nothing has changed on my app in terms of the Godeps file, and I've tried debugging this with more output from my own fork of the buildpack, but I've gotten nowhere.

Is this a known issue at this time? Any advice? FWIW, my last successful push was on 2013/11/14

Thanks!

**Comment by freeformz** [comment]
godep with rewriting and saving deps is the current best practices and we'll evaluate other tooling as the vendoring / deps discussions come to fruition.

Thanks!
