### ISSUE TITLE
Install with multiple main packages with the same named directory

### ISSUE THREAD

**Issue by freeformz** [heroku/heroku-buildpack-go#332]
An internal application *had* the following package structure:

```
github.com/heroku/<repo>/<dira>/cmd/httpd
github.com/heroku/<repo>/<dirb>/cmd/httpd
```

This produced a Procfile of:

```
httpd: bin/httpd
httpd: bin/httpd
```

**Comment by freeformz** [comment]
I think the buildpack should probably throw an error in the case where there are multiple main packages with the same name. The error probably needs to tell the user that they either need to specify a pathspec for installation or rename one of the directories. Thoughts?

**Comment by ghost** [comment]
Internal Work Item: [W-6993089](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000078TKsIAM/view)
