### ISSUE TITLE
bzr installation fails

### ISSUE THREAD

**Issue by telendt** [heroku/heroku-buildpack-go#350]
With buildpack from master
```
-----> Go app detected
-----> Fetching stdlib.sh.v8... done
-----> 
Detected go modules via go.mod
-----> 
       Detected Module Name: github.com/company/REDACTED
-----> 
-----> Using go1.12.7
-----> Installing bzr 2.7.0
-----> Fetching bzr-2.7.0.tar.gz... 
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
 !     Push rejected, failed to compile Go app.
 !     Push failed
```

v126 works fine.

**Comment by atamsingh** [comment]
Hitting the same issue as well.

**Comment by freeformz** [comment]
Fixed. I merged the branch yesterday w/o doing the sync to the bucket.
Maybe I should make the tooling functions fall back to fetching from the source URL if it's not found in the bucket. That's probably sane.

**Comment by freeformz** [comment]
PS: Sorry about this. Will think about doing above and some other options as well.
