### ISSUE TITLE
Is GO_ENV a necessary environment variable?

### ISSUE THREAD

**Issue by frederikhors** [heroku/heroku-buildpack-go#356]
I'm reading around (https://github.com/gobuffalo/buffalo/search?q=GO_ENV&unscoped_q=GO_ENV) about an environment variable called: "`GO_ENV`" and I think it is not a Go "native"/"pure" thing.

Am I wrong?

Am I right?

Do I need to setup this env in my heroku go based apps?

**Comment by freeformz** [comment]
you can see the "standard" go env vars by running `go env`.

AFAICT `GO_ENV` is an attempt to have a [`RAILS_ENV`](https://stackoverflow.com/questions/43863251/where-is-the-rails-env) work alike.

I personally think it's misnamed and should be something like `BUFFALO_ENV`, `GOBUFFALO_ENV`, `GO_BUFFALO_ENV`, etc.

If you set `GO_ENV` in your app's config, it will be available @ runtime, but not at *compile* time. 

The list of what is sourced from the app config at compile time can be found [here](https://github.com/heroku/heroku-buildpack-go/blob/master/lib/common.sh#L208-L221).

**Comment by frederikhors** [comment]
Thanks a lot. Amazing. Thanks.
