### ISSUE TITLE
Adding custom build tags

### ISSUE THREAD

**Issue by crimist** [heroku/heroku-buildpack-go#365]
I was wondering if there's a directive or something for adding build tags to the install process.

### Example

go.mod
```
// +heroku goTags customtag 
```

Build
```
Running: go install -v -tags heroku customtag some/package
```

Cheers.

**Comment by freeformz** [comment]
No, there isn't.

Can you describe your use case so that we can understand the need(s)?

**Comment by crimist** [comment]
My application uses a build tag that modifies certain functions to increase performance while sacrificing metric collection. I'd like to enable that setting on when running on Heroku. 

The reason I use built tags rather than a variable is because by combining constants and build tags the go compiler can optimize out unreachable code which then makes the function smaller and causes the compiler to inline the function.

I could reverse the constants so that you have to opt in for the extensive metrics but I don't really believe that's a good default - you should only enable the performance tags if you need them & don't need the metrics.

**Comment by freeformz** [comment]
This is possible now by using the `heroku` build tag.

```go
// +build existingTag heroku
// ^ existingTag OR heroku : https://golang.org/pkg/go/build/#hdr-Build_Constraints
```

**Comment by freeformz** [comment]
The readme includes this comment: "This buildpack adds a `heroku` build constraint, to enable heroku-specific code."

**Comment by crimist** [comment]
Ah I had totally forgotten about the `OR` keyword. Thanks.

**Comment by Sreyas-Sreelal** [comment]
Sorry it wasn't clear for me.How can i pass fts5 tag for sqlite3 in such way?
