### ISSUE TITLE
Consider supporting gopack

### ISSUE THREAD

**Issue by catsby** [heroku/heroku-buildpack-go#37]
What are your thoughts on adding support for [gopack](https://github.com/d2fn/gopack) as well?

**Comment by freeformz** [comment]
We'll review non godep option sometime in the future as things like [this](https://groups.google.com/forum/#!msg/golang-dev/nMWoEAG55v8/iJGgur7W_SEJ) and [this](https://github.com/kardianos/vendor-spec) come to a conclusion.

Thanks!
