### ISSUE TITLE
go1.13 defaulting

### ISSUE THREAD

**Issue by danp** [heroku/heroku-buildpack-go#376]
https://github.com/heroku/heroku-buildpack-go/pull/366 was meant to change the default from go1.12 to go1.13 but it was discovered in testing that gb seems to have trouble in 1.13.

Before we can have go1.13 be the default, we need to verify this issue and come up with a fix. If gb can't be made to work, a possible way forward is letting folks know that gb is no longer supported when using 1.13+. This may already be the case whether we change the default or not.

**Comment by ghost** [comment]
Internal Work Item: [W-6993081](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000078TJlIAM/view)

**Comment by frederikhors** [comment]
@freeformz any news on this?

**Comment by EtienneM** [comment]
Is there any news on the topic? Is there a reason to keep Go 1.12 as the default version?

**Comment by edmorley** [comment]
The default was updated from Go 1.12 to 1.20 in #540.
