### ISSUE TITLE
 !     error fetching custom buildpack https://github.com/some/buildpack.git    python3

### ISSUE THREAD

**Issue by NOTBYROBOTSONLY** [heroku/heroku-buildpack-go#384]
I am trying to deploy an app on heroku using python3 and I keep getting this error 
 !     error fetching custom buildpack https://github.com/some/buildpack.git

**Comment by hiimtaylorjones** [comment]
Hey there,

Do you mind providing me the output of the following?

```
heroku buildpacks
```

**Comment by hone** [comment]
I'm closing this due to inacitivty. Buildpack fetching is also not something the go buildpack handles directly. If you're doing this on Heroku, please open a support ticket. :purple_heart:

**Comment by JodyZ0203** [comment]
The buildpack does not even exist, so that might be the issue.
