### ISSUE TITLE
 Can't deploy to heroku: App not compatible with buildpack #4 

### ISSUE THREAD

**Issue by IvanDerlich** [heroku/heroku-buildpack-go#385]
`git push heroku master`

Throws this error. 

![Screenshot from 2020-01-14 20-58-15](https://user-images.githubusercontent.com/5816027/72393099-a1b1a600-3710-11ea-94b3-334b43d9cb1b.png)

So then we try to resolve this buildpack issue running:

`heroku create --buildpack https://github.com/heroku/heroku-buildpack-ruby.git`

`git push heroku master`

But the same error persists.

[This](https://github.com/IvanDerlich/Fakebook/blob/f96e805ff0aa332c21d4fb52d6323cb8533f82b0/Gemfile.lock#L1) is our Gemfile.lock
[This](https://github.com/IvanDerlich/Fakebook/blob/f96e805ff0aa332c21d4fb52d6323cb8533f82b0/Gemfile#L1) is our Gemfile
[This](https://github.com/IvanDerlich/Fakebook/tree/f96e805ff0aa332c21d4fb52d6323cb8533f82b0) is the commit in which the problem arises

**Comment by hiimtaylorjones** [comment]
Hey Ivan,

I think this issue is meant for our Ruby Buildpack. Mind opening an issue on [Heroku Support](https://help.heroku.com/) or on the [Github repo](https://github.com/heroku/heroku-buildpack-ruby)?
