### ISSUE TITLE
go_pre_compile does not work

### ISSUE THREAD

**Issue by darmie** [heroku/heroku-buildpack-go#470]
I followed the instructions in the readme for `go.mod` setup, I have compiled a golang executable to be run and generate database specific code before building the actual app, I named the executable `go_pre_compile` and put it in the `bin/` directory relative to the project path... It doesn't work!

```
build myapp.com/api: cannot load myapp.com/api/prisma/db: cannot find module providing package myapp.com/api/prisma/db
 !     Push rejected, failed to compile Go app.
 !     Push failed
```

**Comment by darmie** [comment]
I just figured that the naming convention was wrong, it should have been `go-pre-compile` instead. 

Now, It doesn't have access to the environment variables ....

**Comment by mble** [comment]
@darmie This is a bit unfortunate – as part of the Buildpack API (https://devcenter.heroku.com/articles/buildpack-api), config variables are not available directly during the `compile` step of the buildpack.

Typically, you'd have to reach into `ENV_DIR` and extract them if you need them at compile time.
