### ISSUE TITLE
Does not work with HTTP git push

### ISSUE THREAD

**Issue by freeformz** [heroku/heroku-buildpack-go#5]
At least with `$GO_GIT_DESCRIBE_SYMBOL` set. It works w/o.
```
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 286 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching custom git buildpack... done
remote: -----> Go app detected
remote: -----> Using go1.3.3
remote: fatal: Not a git repository (or any of the parent directories): .git
remote:
remote:  !     Push rejected, failed to compile Go app
remote:
remote: Verifying deploy...
remote:
remote: !	Push rejected to log-shuttle-build.
remote:
To https://git.heroku.com/log-shuttle-build.git
 ! [remote rejected] std_layout -> master (pre-receive hook declined)
```

**Comment by tt** [comment]
This applies to the first push over SSH too.

**Comment by freeformz** [comment]
So what's available at build time that I can use to duplicate this instead of this hack ?

**Comment by freeformz** [comment]
Resolved with the removal of GO_GIT_DESCRIBE_SYMBOL. ATM you can't use the linker to replace strings.

**Comment by tt** [comment]
This is in fact a problem. We rely on this feature for Endosome and based on [this search](https://github.com/search?q=GO_GIT_DESCRIBE_SYMBOL+%40heroku&type=Code&utf8=✓), it's probably required elsewhere too.

**Comment by freeformz** [comment]
Well I need something that will work on both the platform and the kernel. We don't need to actually run the command here and I'm tempted to basically make it this:

`godep go install -ldflags "-X main.version=$VERSION" ./...`

So as long as your various main packages has a `var ( version string )` this just get's embedded properly.

**Comment by freeformz** [comment]
Something like the above would also be build environment agnostic (as long as the ENV var was supplied by the build team). This way github integration could "set the right thing" there as well.

**Comment by sclasen** [comment]
still unclear to me why this broke? it used to work...

**Comment by freeformz** [comment]
@sclasen It was removed from upstream and it doesn't work on the platform with HTTP git pushes because the build pack isn't evoked in a git directory.

**Comment by tt** [comment]
I'd like to still support being able to specify the symbol; we can default to `main.version` alright, but it may not be how you wire up your application.

I think reading `VERSION` is a good suggestion and considering we already have that in the build API, it should be straightforward to pass through to the buildpack.

**Comment by freeformz** [comment]
@sclasen because it relies on a git repo and the git repo isn't there reliably.

@tt I'm fine with still being able to specify the symbol, but defaulting to main.version, but IMO you're likely using it wrong (I did that at first as well) most other ways that I've seen it being used.

**Comment by freeformz** [comment]
@tt So, when can I/we have $VERSION (or whatever you guys decide) in the build environment?
