### ISSUE TITLE
Go 1.22 apps cannot be built after the version change to go1.22.4

### ISSUE THREAD

**Issue by HCoban** [heroku/heroku-buildpack-go#559]
After the [recent change ](https://github.com/heroku/heroku-buildpack-go/pull/558) to add go 1.22.4, builds fail with the following error

```
-----> New Go Version, clearing old cache
-----> Installing go1.22.4
-----> Fetching go1.22.4.linux-amd64.tar.gz... curl: (22) The requested URL returned error: 403
 !     Push rejected, failed to compile Go app.
 !     Push failed
```

**Comment by joshwlewis** [comment]
@HCoban The 1.22.4 and 1.22.11 assets weren't available in s3 for a time. This has been fixed and your build should work again. Sorry for the trouble.
