### ISSUE TITLE
Erroneous Error Message on Build Failure

### ISSUE THREAD

**Issue by ceiroa** [heroku/heroku-buildpack-go#69]
There are cases where the build fails, but the error message is erroneous:

![screen shot 2014-12-12 at 10 20 16 am](https://cloud.githubusercontent.com/assets/1894238/5414920/98ce4a6c-81e8-11e4-839e-5ac526e9466a.png)

First, it directs you to http://mmcgrana.github.io/2012/09/getting-started-with-go-on-heroku for info on how to configure a .godir file, but there is no reference to .godir on that tutorial.

Second, I don't think lack of a .godir file is the problem. I received that message on another application that I was finally able to get working, without adding a .godir. I believe it was a folder structure issue in that case.

**Comment by freeformz** [comment]
I've updated the link to point to my own, more up-to-date post. Thanks for pointing this out.
