### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by kevinburkeshyp** [heroku/heroku-buildpack-go#75]
I know this isn't quite the go way, but would be useful indicators of library growth etc..

**Comment by freeformz** [comment]
What do you mean by this? Can you provide an example of setup / what you would expect?

**Comment by kevinburkeshyp** [comment]
When you commit/push a significant change, increment a version number and run `git tag x.y.z`

**Comment by freeformz** [comment]
How would the buildpack know it's a "significant change"? What if the build isn't being run from git? We don't always have access to the git repo. IMO this is something you should do as a developer as part of release management / code organization.

**Comment by kevinburkeshyp** [comment]
I'm talking about this repo specifically. When you (@freeformz) make a change to this project, tag a new version. That way I can pin my buildpack dependency to a specific git tag, instead of having to read through the commit history, or leave my buildpack dependency floating on whatever HEAD of this repo is pointing to.

**Comment by freeformz** [comment]
@kevinburkeshyp Ahh okay thanks. We'll do something here, not sure exactly what yet though.

**Comment by cyx** [comment]
With the advent of https://elements.heroku.com/, we'll definitely comply
with the standards, e.g.:

1) CHANGELOG.md
2) Release tags

@freeformz I would tag anything that's merged to master (that's not a
README / doc fix). Thoughts?

**Comment by freeformz** [comment]
@cyx Was basically thinking of tagging releases, should probably tag all the things for now though. Def a changelog.
