### ISSUE TITLE
Go 1.4.2 released!

### ISSUE THREAD

**Issue by TrollWarlord** [heroku/heroku-buildpack-go#77]
Can we upgrade this build pack to 1.4.2 please! 

https://golang.org/doc/devel/release.html

go1.4.2 (released 2015/02/17) includes bug fixes to the go command, the compiler and linker, and the runtime, syscall, reflect, and math/big packages. See the Go 1.4.2 milestone on our issue tracker for details.

**Comment by freeformz** [comment]
You may want to check out https://github.com/heroku/heroku-buildpack-go

**Comment by freeformz** [comment]
Also if you are using godeps, 1.4.2 is already supported, just bump your godep file.
