### ISSUE TITLE
Error fetching custom buildback

### ISSUE THREAD

**Issue by ijt** [heroku/heroku-buildpack-go#8]
Here's what happens:

[ issactrotts ~/go_workspace/src/example.com/server ] heroku create -s cedar --buildpack git@github.com:kr/heroku-buildpack-go.git
Creating immense-depths-6065... done, stack is cedar
BUILDPACK_URL=git@github.com:kr/heroku-buildpack-go.git
http://immense-depths-6065.herokuapp.com/ | git@heroku.com:immense-depths-6065.git
Git remote heroku added
[ issactrotts ~/go_workspace/src/example.com/server ] git push heroku master
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (5/5), 539 bytes, done.
Total 5 (delta 0), reused 0 (delta 0)

-----> Heroku receiving push
-----> Fetching custom buildpack... failed
 !     Heroku push rejected, error fetching custom buildpack

To git@heroku.com:immense-depths-6065.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:immense-depths-6065.git'

**Comment by nathan-sixnines** [comment]
I had a similar problem with https://github.com/heroku/heroku-buildpack-apt

For me this worked:

heroku config:add BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-apt
Setting BUILDPACK_URL and restarting ⬢ flask-kaji... done, v578
BUILDPACK_URL: https://github.com/heroku/heroku-buildpack-apt

Very similar to what @ijt did but for some reason it only worked without the ".git" at the end of the url.

**Comment by freeformz** [comment]
BTW: BUILDPACK_URL is basically deprecated, instead use `heroku config:unset BUILDPACK_URL;  heroku buildpacks:set https://github.com/heroku/heroku-buildpack-apt.git`. You can find more info here: https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app

**Comment by igorsquadra** [comment]
If someone still has this issue with nodejs for me worked `heroku buildpacks:set heroku/nodejs` and `git push heroku master`. Here is Heroku documentation https://devcenter.heroku.com/articles/buildpacks#detection-failure

**Comment by Srk1122205** [comment]
I am facing this problem 

App not compatible with buildpack: https://github.com/Srk1122205/Paradise_Parking
       bash: /tmp/codon/tmp/buildpacks/190d1fcedf8cc1ab8b279afb8c2d94e816f1b74d/bin/detect: No such file or directory
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
