### ISSUE TITLE
GOPATH missing "o"

### ISSUE THREAD

**Issue by austinpray** [heroku/heroku-buildpack-go#81]
https://github.com/heroku/heroku-buildpack-go/blob/6eeb09f5372b23a844bc27302f205a82be9ac4f8/bin/compile#L103

I see:

```
GOPATH=$build/.heroku/g export GOPATH
```

When I expect it to be:

```
GOPATH=$build/.heroku/go export GOPATH
```

Do you guys agree?

**Comment by cyx** [comment]
Yes great catch.

**Comment by austinpray** [comment]
went ahead and patched it: https://github.com/heroku/heroku-buildpack-go/pull/82

**Comment by kr** [comment]
The choice of `g` was deliberate, but `go` is ok too. It doesn't really matter.

**Comment by austinpray** [comment]
@kr ah, I see. thanks for clarifying. IMO this change makes it much more clear as to what is going on. Especially with [how the go docs are written](https://golang.org/doc/code.html) regarding GOPATH: `GOPATH=$HOME/go`
