### ISSUE TITLE
should verify Godeps and Godeps.json file format prior to parsing by jq

### ISSUE THREAD

**Issue by shawnzhu** [heroku/heroku-buildpack-go#86]
I asked [this question](http://stackoverflow.com/questions/31191580/compiling-error-when-using-community-golang-buildpack-on-bluemix/31192084#31192084) for help from stackoverflow about following error message reported from buildpack:

``` shell
-----> Downloaded app package (556K)
Cloning into '/tmp/buildpacks/buildpack-go'...
Submodule 'compile-extensions' (https://github.com/cloudfoundry-incubator/compile-extensions.git) registered for path 'compile-extensions'
Cloning into 'compile-extensions'...
Submodule path 'compile-extensions': checked out 'f752ecf4b27d2f31bb082dfe7a47c76fefc769d7'
-------> Buildpack version 1.4.0
parse error: Expected separator between values at line 32, column 3
Staging failed: Buildpack compilation step failed
```
## root cause

It costs me some time to locate this `parse error` because it doesn't provide any information about context. Although I figured it out that it was caused by a missing comma from `Godeps/Godeps.json` during code merge. since I can not reproduce this locally since all dependencies in `_workspace` is ready and I can not discover this json file format until running command `godep update`.
## expectation

it should verify Godeps or Godeps.json file format during compiling although it just reads `ImportPath` and `GoVersion` in `bin/compile`.

**Comment by kr** [comment]
We could do this with something like

```
if ! <Godeps/Godeps.json jq -r '""'
then
  echo bad Godeps.json
  exit 1
fi
```

modulo bikeshedding.
