### ISSUE TITLE
Support for Nut

### ISSUE THREAD

**Issue by ebramanti** [heroku/heroku-buildpack-go#91]
It would be great if this buildpack supported [Nut](https://github.com/jingweno/nut), a pretty popular dependency manager for Go. I'm working on this on a fork, but I'm curious if anyone else is interested in having this added to the buildpack.

**Comment by bithavoc** [comment]
:+1:

**Comment by ebramanti** [comment]
@bithavoc I've gotten it to work somewhat, but I've pretty much broken the buildpack's normal functionality to do it. Can you try forking and seeing if you can make any progress?

**Comment by freeformz** [comment]
Personally (not speaking for my position @ Heroku) I'd much rather spend time adding support for vendor-spec, which all of these tools should support, especially as Go 1.6 approaches. I am working towards that with godep atm (albeit slowly).

With that said (putting my Heroku hat on). Is there sufficient interest in supporting NUT? The author of which also works @ Heroku. If you want support for https://github.com/jingweno/nut please +1 this issue.

**Comment by ebramanti** [comment]
:+1:

**Comment by ebramanti** [comment]
@jingweno would you be interested in seeing support for this with Heroku?

**Comment by owenthereal** [comment]
I :+1: to this. But that may require changes to `nut` to declare Go version etc. that the buildpack needs.

**Comment by bithavoc** [comment]
I second @freeformz on this.

**Comment by ebramanti** [comment]
@bithavoc second on vendor support or Nut?

**Comment by freeformz** [comment]
@jadengore IMO Nut + godep + buildpack supporting the vendor spec is the best outcome, but I understand the argument for interim support of Nut though, as long as nut provides all of the information necessary to compile the code reproducibly (like go version).

**Comment by ebramanti** [comment]
@freeformz I have Nut working specifically for the app I'm working on, but my fork has significantly diverged and I don't have too much shell scripting experience to know if this is ready for public release.

What I plan to do is iterate on my work and have a PR for discussion/amendments so that maybe we can get this merged in with Nut support.

**Comment by freeformz** [comment]
@jadengore SGTM Having something to review is probably best.

**Comment by freeformz** [comment]
Can Nut not support the vendor-spec instead?

**Comment by freeformz** [comment]
We're not going to be supporting nut, in fact I'd like to reduce the number of supported tools. Hopefully dep and the other plans around future dependency management stuff in go 1.10/11/etc will make that a reality.
