### ISSUE TITLE
tests exercising the go linker functionality

### ISSUE THREAD

**Issue by mavenraven** [heroku/heroku-buildpack-go#99]
Hi there,
We're about to pull this change from you into our buildpack:
https://github.com/heroku/heroku-buildpack-go/commit/a0a82e1a3fc0d0a2158b24826b2e6c45559799cd

We wrote these tests to exercise this functionality if you're interested in pulling them in:
https://github.com/cloudfoundry/go-buildpack/commit/3a6deb112ffe2da76614de1c350f904d9192d859

Thanks!

**Comment by flavorjones** [comment]
For full context, the Cloud Foundry team maintains a buildpack that's downstream from heroku's buildpack.

The `-ldflags` feature didn't have test coverage, so we added test coverage downstream. This ticket is just pointing out our tests, in case Heroku wants to pull them in (or do something similar) in the Heroku repo.

Thanks!

**Comment by freeformz** [comment]
There is now a test for this when using godep, but handling is the same no matter which manager is in use atm: https://github.com/heroku/heroku-buildpack-go/blob/master/test/run#L112-L127
